baseURL: 'https://dirkk.github.io/vrojauchzend/'
languageCode: 'de-de'
title: 'VroJAuchzenD'
theme: 'vrojauchzend-theme'

params:
  description: 'VroJAuchzenD'
  author: 'Vroni, Johannes, Aurelia, Dirk'
  email: 'vrojauchzend@posteo.de'

markup:
  goldmark:
    renderer:
      unsafe: true

outputs:
  home:
    - HTML
    - RSS